CREATE TABLE IF NOT EXISTS "__EFMigrationsHistory" (
    "MigrationId" character varying(150) NOT NULL,
    "ProductVersion" character varying(32) NOT NULL,
    CONSTRAINT "PK___EFMigrationsHistory" PRIMARY KEY ("MigrationId")
);

START TRANSACTION;

CREATE EXTENSION IF NOT EXISTS vector;

CREATE TABLE brands (
    id integer GENERATED BY DEFAULT AS IDENTITY,
    name character varying(100) NOT NULL,
    CONSTRAINT "PK_brands" PRIMARY KEY (id)
);

CREATE TABLE carts (
    id uuid NOT NULL,
    session_id text,
    user_id uuid,
    status text NOT NULL,
    customer_note text,
    created_at timestamp with time zone NOT NULL,
    CONSTRAINT "PK_carts" PRIMARY KEY (id)
);

CREATE TABLE categories (
    id integer GENERATED BY DEFAULT AS IDENTITY,
    name character varying(50) NOT NULL,
    parent_id integer,
    CONSTRAINT "PK_categories" PRIMARY KEY (id),
    CONSTRAINT "FK_categories_categories_parent_id" FOREIGN KEY (parent_id) REFERENCES categories (id)
);

CREATE TABLE users (
    id uuid NOT NULL,
    username character varying(50) NOT NULL,
    password_hash text NOT NULL,
    role character varying(20) NOT NULL,
    full_name character varying(100),
    created_at timestamp with time zone NOT NULL,
    is_active boolean NOT NULL,
    CONSTRAINT "PK_users" PRIMARY KEY (id)
);

CREATE TABLE products (
    id uuid NOT NULL,
    code character varying(50) NOT NULL,
    name character varying(200) NOT NULL,
    description text,
    suggested_price numeric NOT NULL,
    cost_price numeric,
    cost_code character varying(20),
    image_url text,
    category_id integer,
    brand_id integer,
    CONSTRAINT "PK_products" PRIMARY KEY (id),
    CONSTRAINT "FK_products_brands_brand_id" FOREIGN KEY (brand_id) REFERENCES brands (id),
    CONSTRAINT "FK_products_categories_category_id" FOREIGN KEY (category_id) REFERENCES categories (id)
);

CREATE TABLE cart_items (
    id uuid NOT NULL,
    cart_id uuid NOT NULL,
    product_id uuid NOT NULL,
    quantity integer NOT NULL,
    added_at timestamp with time zone NOT NULL,
    CONSTRAINT "PK_cart_items" PRIMARY KEY (id),
    CONSTRAINT "FK_cart_items_carts_cart_id" FOREIGN KEY (cart_id) REFERENCES carts (id) ON DELETE CASCADE,
    CONSTRAINT "FK_cart_items_products_product_id" FOREIGN KEY (product_id) REFERENCES products (id) ON DELETE CASCADE
);

CREATE TABLE product_images (
    id uuid NOT NULL,
    product_id uuid NOT NULL,
    image_url text NOT NULL,
    created_at timestamp with time zone NOT NULL,
    CONSTRAINT "PK_product_images" PRIMARY KEY (id),
    CONSTRAINT "FK_product_images_products_product_id" FOREIGN KEY (product_id) REFERENCES products (id) ON DELETE CASCADE
);

CREATE INDEX "IX_cart_items_cart_id" ON cart_items (cart_id);

CREATE INDEX "IX_cart_items_product_id" ON cart_items (product_id);

CREATE INDEX "IX_categories_parent_id" ON categories (parent_id);

CREATE INDEX "IX_product_images_product_id" ON product_images (product_id);

CREATE INDEX "IX_products_brand_id" ON products (brand_id);

CREATE INDEX "IX_products_category_id" ON products (category_id);

CREATE UNIQUE INDEX "IX_products_code" ON products (code);

CREATE UNIQUE INDEX "IX_users_username" ON users (username);

INSERT INTO "__EFMigrationsHistory" ("MigrationId", "ProductVersion")
VALUES ('20260217045919_AddBrandEntity', '8.0.0');

COMMIT;

