using Microsoft.EntityFrameworkCore;
using MtcSales.API.Data;

var builder = WebApplication.CreateBuilder(args);

// Render sets the PORT environment variable.
// If running on Render, we need to bind to http://0.0.0.0:PORT
var port = Environment.GetEnvironmentVariable("PORT") ?? "8080";
builder.WebHost.UseUrls($"http://*:{port}");

// Add services to the container.
var connectionString = builder.Configuration.GetConnectionString("DefaultConnection");
builder.Services.AddDbContext<MtcContext>(options =>
    options.UseNpgsql(connectionString));

builder.Services.AddControllers();
builder.Services.AddEndpointsApiExplorer();
builder.Services.AddSwaggerGen();

// Add CORS
builder.Services.AddCors(options =>
{
    options.AddPolicy("AllowAll",
        policy =>
        {
            policy.SetIsOriginAllowed(origin => true) // Allow any origin
                   .AllowAnyMethod()
                   .AllowAnyHeader()
                   .AllowCredentials(); // Allow credentials (cookies, auth headers)
        });
});

var app = builder.Build();

// Configure the HTTP request pipeline.
app.UseCors("AllowAll"); // CORS must be first

if (app.Environment.IsDevelopment())
{
    app.UseSwagger();
    app.UseSwaggerUI();
}

app.UseStaticFiles();

app.UseHttpsRedirection();

app.UseAuthorization();

app.MapControllers();

// Health check endpoint
app.MapGet("/", () => new { status = "online", version = "1.0.1", message = "MTC Sales API is running" });


// Run schema update on startup (for MVP deployment)
using (var scope = app.Services.CreateScope())
{
    var context = scope.ServiceProvider.GetRequiredService<MtcContext>();
    try
    {
        // Force execution of schema update using embedded SQL string
        // This avoids file path issues on Render/Linux environments
        var sql = @"
    -- Basic Tables
    CREATE TABLE IF NOT EXISTS brands (
        id integer GENERATED BY DEFAULT AS IDENTITY,
        name character varying(100) NOT NULL,
        CONSTRAINT ""PK_brands"" PRIMARY KEY (id)
    );

    CREATE TABLE IF NOT EXISTS categories (
        id integer GENERATED BY DEFAULT AS IDENTITY,
        name character varying(50) NOT NULL,
        parent_id integer,
        CONSTRAINT ""PK_categories"" PRIMARY KEY (id),
        CONSTRAINT ""FK_categories_categories_parent_id"" FOREIGN KEY (parent_id) REFERENCES categories (id)
    );

    CREATE TABLE IF NOT EXISTS product_images (
        id uuid NOT NULL,
        product_id uuid NOT NULL,
        image_url text NOT NULL,
        created_at timestamp with time zone NOT NULL,
        CONSTRAINT ""PK_product_images"" PRIMARY KEY (id),
        CONSTRAINT ""FK_product_images_products_product_id"" FOREIGN KEY (product_id) REFERENCES products (id) ON DELETE CASCADE
    );

    CREATE TABLE IF NOT EXISTS carts (
        id uuid NOT NULL,
        session_id text,
        user_id uuid,
        status text NOT NULL DEFAULT 'active',
        customer_note text,
        created_at timestamp with time zone NOT NULL,
        CONSTRAINT ""PK_carts"" PRIMARY KEY (id)
    );

    CREATE TABLE IF NOT EXISTS cart_items (
        id uuid NOT NULL,
        cart_id uuid NOT NULL,
        product_id uuid NOT NULL,
        quantity integer NOT NULL,
        added_at timestamp with time zone NOT NULL,
        CONSTRAINT ""PK_cart_items"" PRIMARY KEY (id),
        CONSTRAINT ""FK_cart_items_carts_cart_id"" FOREIGN KEY (cart_id) REFERENCES carts (id) ON DELETE CASCADE,
        CONSTRAINT ""FK_cart_items_products_product_id"" FOREIGN KEY (product_id) REFERENCES products (id) ON DELETE CASCADE
    );

    -- Indices
    CREATE INDEX IF NOT EXISTS ""IX_cart_items_cart_id"" ON cart_items (cart_id);
    CREATE INDEX IF NOT EXISTS ""IX_cart_items_product_id"" ON cart_items (product_id);

    -- Column Checks and Updates
    DO $$
    BEGIN
        -- Products Table Updates
        IF NOT EXISTS (SELECT 1 FROM information_schema.columns WHERE table_name = 'products' AND column_name = 'brand_id') THEN
            ALTER TABLE products ADD COLUMN brand_id integer;
            ALTER TABLE products ADD CONSTRAINT ""FK_products_brands_brand_id"" FOREIGN KEY (brand_id) REFERENCES brands (id);
            CREATE INDEX ""IX_products_brand_id"" ON products (brand_id);
        END IF;

        IF NOT EXISTS (SELECT 1 FROM information_schema.columns WHERE table_name = 'products' AND column_name = 'category_id') THEN
            ALTER TABLE products ADD COLUMN category_id integer;
            ALTER TABLE products ADD CONSTRAINT ""FK_products_categories_category_id"" FOREIGN KEY (category_id) REFERENCES categories (id);
            CREATE INDEX ""IX_products_category_id"" ON products (category_id);
        END IF;

        IF NOT EXISTS (SELECT 1 FROM information_schema.columns WHERE table_name = 'products' AND column_name = 'quantity') THEN
            ALTER TABLE products ADD COLUMN quantity integer NOT NULL DEFAULT 0;
        END IF;

        IF NOT EXISTS (SELECT 1 FROM information_schema.columns WHERE table_name = 'products' AND column_name = 'cost_price') THEN
            ALTER TABLE products ADD COLUMN cost_price numeric;
        END IF;

        IF NOT EXISTS (SELECT 1 FROM information_schema.columns WHERE table_name = 'products' AND column_name = 'cost_code') THEN
            ALTER TABLE products ADD COLUMN cost_code character varying(20);
        END IF;

        IF NOT EXISTS (SELECT 1 FROM information_schema.columns WHERE table_name = 'products' AND column_name = 'image_url') THEN
            ALTER TABLE products ADD COLUMN image_url text;
        END IF;

        -- Carts Table Updates
        IF NOT EXISTS (SELECT 1 FROM information_schema.columns WHERE table_name = 'carts' AND column_name = 'session_id') THEN
            ALTER TABLE carts ADD COLUMN session_id text;
        END IF;
        
        IF NOT EXISTS (SELECT 1 FROM information_schema.columns WHERE table_name = 'carts' AND column_name = 'user_id') THEN
            ALTER TABLE carts ADD COLUMN user_id uuid;
        END IF;

        IF NOT EXISTS (SELECT 1 FROM information_schema.columns WHERE table_name = 'carts' AND column_name = 'status') THEN
        ALTER TABLE carts ADD COLUMN status text NOT NULL DEFAULT 'active';
    END IF;

    IF NOT EXISTS (SELECT 1 FROM information_schema.columns WHERE table_name = 'carts' AND column_name = 'customer_note') THEN
        ALTER TABLE carts ADD COLUMN customer_note text;
    END IF;

    -- Cart Items Table Updates
    IF NOT EXISTS (SELECT 1 FROM information_schema.columns WHERE table_name = 'cart_items' AND column_name = 'added_at') THEN
        ALTER TABLE cart_items ADD COLUMN added_at timestamp with time zone NOT NULL DEFAULT NOW();
    END IF;
    END $$;
    ";
        context.Database.ExecuteSqlRaw(sql);
        Console.WriteLine("Schema updated successfully from embedded SQL");
    }
    catch (Exception ex)
    {
        Console.WriteLine($"Error updating schema: {ex.Message}");
    }
}

app.Run();
