CREATE TABLE IF NOT EXISTS brands (
    id integer GENERATED BY DEFAULT AS IDENTITY,
    name character varying(100) NOT NULL,
    CONSTRAINT "PK_brands" PRIMARY KEY (id)
);

CREATE TABLE IF NOT EXISTS categories (
    id integer GENERATED BY DEFAULT AS IDENTITY,
    name character varying(50) NOT NULL,
    parent_id integer,
    CONSTRAINT "PK_categories" PRIMARY KEY (id),
    CONSTRAINT "FK_categories_categories_parent_id" FOREIGN KEY (parent_id) REFERENCES categories (id)
);

DO $$
BEGIN
    IF NOT EXISTS (SELECT 1 FROM information_schema.columns WHERE table_name = 'products' AND column_name = 'brand_id') THEN
        ALTER TABLE products ADD COLUMN brand_id integer;
        ALTER TABLE products ADD CONSTRAINT "FK_products_brands_brand_id" FOREIGN KEY (brand_id) REFERENCES brands (id);
        CREATE INDEX "IX_products_brand_id" ON products (brand_id);
    END IF;

    IF NOT EXISTS (SELECT 1 FROM information_schema.columns WHERE table_name = 'products' AND column_name = 'category_id') THEN
        ALTER TABLE products ADD COLUMN category_id integer;
        ALTER TABLE products ADD CONSTRAINT "FK_products_categories_category_id" FOREIGN KEY (category_id) REFERENCES categories (id);
        CREATE INDEX "IX_products_category_id" ON products (category_id);
    END IF;

    IF NOT EXISTS (SELECT 1 FROM information_schema.columns WHERE table_name = 'products' AND column_name = 'quantity') THEN
        ALTER TABLE products ADD COLUMN quantity integer NOT NULL DEFAULT 0;
    END IF;
END $$;
